---
title: "Dissertation"
author: "Y YANG"
date: "20/06/2017"
output: pdf_document
---
**Use _texreg_ (or _stargazer_, _apsrtable_ or equivalent) to present results in tabular form. You can also use _coefplot_ style plots (or any other visualisation of results).**
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
```

```{r}
#open csv

data42 <- read.csv("https://raw.githubusercontent.com/YangYue93/Dissertation_Public_Opinion/master/Data42.csv",
                   header = TRUE)
data42 <- data42[,-1]
data20 <- read.csv("https://raw.githubusercontent.com/YangYue93/Dissertation_Public_Opinion/master/Data20.csv",
                   header = TRUE)
data20 <- data20[,-1]
```

```{r}
#DATA DESCRIPTION 
#add countries names
#select only year 2015

data2015 <- data42 %>%
  filter(Time == "2015")

data2008 <- data42 %>%
  filter(Time == "2008")

gg <- cbind(data2015[,c(1,6)],data2008[,6])
colnames(gg) <- c("Country","Public Opinion 2008","Public Opinion 2015")

sPDF <- joinCountryData2Map(data2015,joinCode="NAME",nameJoinColumn="Country.Name")
mapDevice() #create world map shaped window
mapCountryData(sPDF,nameColumnToPlot='Pub.Opinion')


sPDF <- joinCountryData2Map(data2015,joinCode="NAME",nameJoinColumn="Country.Name")
mapDevice() #create world map shaped window
mapCountryData(sPDF,nameColumnToPlot='Member')

#ggplot line
ggplot(data=data42, aes(x=data42$Time, y=data42$Pub.Opinion, group=data42$Country.Name, colour=data42$Country.Name)) +
    geom_line() +
    geom_point()

#加一个趋势图
attach(gg)

ggplot(gg, aes(x=`Public Opinion 2008`, y= `Public Opinion 2015`, colour=Country, label=Country))+
  geom_point() +geom_text(aes(label=Country),hjust=0, vjust=0)

ggplot(mtcars, aes(x='wt', y='mpg', label='name')) +
    geom_text()
```



```{r}


#add change of opinion
data2008 <- data42 %>%
  filter(Time == "2008")

data2015$Change.Opi <- data2015$Pub.Opinion - data2008$Pub.Opinion


attach(data2015)
#remove china
data2015 <- data2015[-6,]

#create log variable of opinion change
data2015$abs.change <- abs(data2015$Change.Opi)
data2015$log.change <- log(data2015$abs.change)
data2015$log.gdp <- log(data2015$GDP)
```

```{r}
#add vote variable
#UNGA VOTING DATA

vote <- read.csv("/Users/moony/Downloads/ChinaUNGAVoting.csv")
vote$ccode1 <- countrycode(vote$ccode1, "cown" , "country.name")
names(vote)[names(vote)=="ccode1"] <- "Country.Name"
vote$ccode2 <- countrycode(vote$ccode2, "cown" , "country.name")
names(vote)[names(vote)=="ccode2"] <- "China"

vote <- vote %>%
  filter(year == "2014")
vote <- vote[,-1]

vote <- vote[,c(1,5:7)]
vote$Country.Name <- countrycode(vote$Country.Name, "country.name", "cown")

data2015$name <- countrycode(data2015$Country.Name, "country.name", "cown")

data2015 <- merge(x = data2015, y = vote, 
             by.x = "name" , by.y = "Country.Name")

vote2 <- read.csv("/Users/moony/Desktop/Dissertation/data/vote.csv", header = TRUE)


```



```{r}
#stage first
#covariation model
cov(data2015$Member,data2015$Change.Opi)
# [1] -1.294512

#OLS
attach(data2015)
log1 <- glm(Member ~ Region + Polity.Sim + Change.Opi + GDP.Growth + absidealdiff, 
           data = data2015,
           family = binomial(link='logit'))
log2 <- glm(Member ~ Change.Opi, 
           family = binomial(link='logit'),
           data = data2015)
log3 <- glm(Member ~ GDP.Growth, 
           family = binomial(link='logit'),
           data = data2015)
log4 <- glm(vote2$membership~vote2$absidealdiff, 
           family = binomial(link='logit'),
           data = vote2)

anova(log1,log2,log3,log4,
      test="Chisq")

screenreg(log1,log2,log3,log4)

library(stargazer)
stargazer::stargazer(log1,log2,log3,log4, title="Results", type = "html", align=TRUE)
stargazer(data2015)

new <- read.csv("/Users/moony/Desktop/Dissertation/data/allnewdata.csv", header = T)
new <- new[,-1]

new$import.dependence <- as.numeric(new$import.dependence)

attach(new)
log1 <- glm(membership ~ absidealdiff + polity.diff + Import.from.china + GDP + Opinion.Change,
            family = binomial(link='logit'),
            data = new)
log2 <- glm(membership ~ Opinion.Change,
            family = binomial(link='logit'),
            data = new)
log3 <- glm(membership ~ absidealdiff,
            family = binomial(link='logit'),
            data = new)
log4 <- glm(membership ~ polity.diff,
            family = binomial(link='logit'),
            data = new)


log5 <- glm(membership ~ Import.from.china,
            family = binomial(link='logit'),
            data = new)

anova(log1,log2,log3,log4,log5,
      test="Chisq")
library(apsrtable)
apsrtable(log1,log2,log3,log4,log5)
```

```{r}
#logit regression
set.seed(1)

train <- sample(nrow(data2015)/2 , replace = FALSE)
test <- -train
data.train <- data2015[train,]
data.test <- data2015[test,]

#logit regression with all variables
log <- glm(data2015$Member ~ data2015$Region + data2015$Polity + data2015$GDP +
             data2015$Capital + data2015$Air + data2015$Debt + data2015$Change.Opi, 
           family = binomial(link='logit'), data = data2015)
summary(log)

#opinion change and capital
log1 <- glm(data2015$Member ~ data2015$Change.Opi + data2015$Capital, 
           family = binomial(link='logit'), data = data2015)

summary(log1)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.0756  -0.9070  -0.5919   0.9455   1.6908  

Coefficients:
                     Estimate Std. Error z value Pr(>|z|)  
(Intercept)         -1.142530   0.582930  -1.960   0.0500 *
data2015$Change.Opi -0.034915   0.029409  -1.187   0.2351  
data2015$Capital     0.022582   0.009606   2.351   0.0187 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 56.814  on 40  degrees of freedom
Residual deviance: 47.332  on 38  degrees of freedom
AIC: 53.332

Number of Fisher Scoring iterations: 4

#remove leverage countries
select <- data2015 [-c(3,4,13,16,19,24),]

log2 <- glm(select$Member ~ select$Change.Opi,
            family = binomial(link = 'logit'), data = select)
summary(log2)
#the coefficient of opinion change becomes positive
```


```{r}
#regression model on member countries
set.seed(1)

#all
lr <- glm(data20$Share ~ data20$Polity.Sim + data20$Region + data20$Pub.Opinion + data20$GDP +
            data20$Capital + data20$Air + data20$Debt, data = data20, family = gaussian)
summary(lr)

#
lr1 <- glm(data20$Share ~ data20$Pub.Opinion : data20$GDP,
           data = data20, family = gaussian)
summary(lr1)

#debt,gdp,

#creat df with opinion change of 20 countries
datachange <- data2015 %>%
  filter(Member == "1")

lr2 <- glm(datachange$Share ~ datachange$Pub.Opinion : datachange$GDP + datachange$Change.Opi,
           data = datachange, family = gaussian)
summary(lr2)

#add imf voting share
datachange$IMF <- c(1.34, 2.22, 2.22, 0.43, 4.04, 5.33, 2.64, 0.95, 0.41, 3.03,
                    0.1, 0.75, 0.43, 0.44, 0.84, 2.59, 0.64, 1.93, 4.04, 0.26)
datachange$IMF.Share <- c(6572.4,11042,11023,2037.1,20155.1,
                          26634.4,13114.4,4648.4,1920.9,15070,
                          343.1,3633.8,2031,2042.9,4095.4,
                          12903.7,3051.2,9535.5,20155.1,1153.1)
datachange$sharedifference <- datachange$IMF.Share - datachange$Share

cov(datachange$sharedifference, datachange$Change.Opi)
#[1] 5931.912

lr3 <- glm(datachange$sharedifference ~ datachange$Pub.Opinion + datachange$Pub.Opinion : datachange$Polity,
           data = datachange, family = gaussian)
summary(lr3)
```

```{r}
#logit regression
set.seed(0)
sub <- my.data[,-c(1,2,5,4,7,9,13,14,16)]
#logit regression with glm

lr <- glm(aiib.member ~ Pub.Opinion + Polity, data = my.data, family = gaussian)
summary(lr)

#gam
gr <-gam(total.subscrip ~ ., data = sub, family = gaussian)
summary(gr)

train <- sample(nrow(sub)/2 , replace = FALSE)
test <- -train
sub.train <- sub[train,]
sub.test <- sub[test,]

gr.train <- gam(total.subscrip ~ ., data = sub.train, family = gaussian)
predict(gr.train, type = "terms", newdata = sub.test)

gl <- glm(total.subscrip ~ Pub.Opinion + Polity, family = gaussian, data = my.data)
```

